services: 
  websocket-php:
    container_name: websocket-php
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    build:
      context: ./socket
      dockerfile: Dockerfile
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

