services: 
  websocket-php:
    container_name: websocket-php
    restart: unless-stopped
    ports:
      - 8080:8080
    build:
      context: ./socket
      dockerfile: Dockerfile
    networks:
      - backend_net
# deploy
  # nginx:
  #   image: nginx:1.19
  #   container_name: websocket-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - websocket-php
  #   networks:
  #     - backend_net

networks:
  backend_net:
    driver: bridge

